<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Article;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{

    public function searchBy($searchstring)
    {
        return $this->createQueryBuilder('a')
            ->where('a.title  LIKE :param')
            ->orWhere('a.description  LIKE :param')
            ->orWhere('a.content  LIKE :param')
            ->setParameter('param', '%' . $searchstring .'%')
            ->getQuery()
            ->getResult();
    }

}