<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;


/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function searchBy($searchstring)
    {
        return $this->createQueryBuilder('u')
            ->where('u.firstName  LIKE :param')
            ->orWhere('u.lastName  LIKE :param')
            ->orWhere('u.login  LIKE :param')
            ->setParameter('param', '%' . $searchstring .'%')
            ->getQuery()
            ->getResult();
    }

}
